name: pharmacyapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flappy_search_bar: ^1.7.2
  validators: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

